server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: "pk2258"

  profiles:
    active: dev

  jackson:
    serialization:
      fail-on-empty-beans: false

  # MySQL 연결 정보 (현재 주석 처리됨)
  # datasource:
  #   url: jdbc:mysql://localhost/awsTestDb?useSSL=false&allowPublicKeyRetrieval=true
  #   username: root
  #   password: pk2258
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   hikari:
  #     auto-commit: false

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL  # ✅ INIT 제거됨
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true  # ✅ JPA 먼저 실행되고 data.sql 그다음 실행
    hibernate:
      ddl-auto: create-drop                      # ✅ 테이블 자동 생성
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show-sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always  # ✅ schema.sql과 data.sql 항상 실행되도록 설정
      continue-on-error: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: true

  mail:
    host: smtp.gmail.com
    port: 465
    username: bid.system.info@gmail.com
    password: tskqfpdczojlwfbh
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          timeout: 20000
          connectiontimeout: 20000
          writetimeout: 20000
          starttls:
            enable: true

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
