server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: "pk2258"

  profiles:
    active: dev

  jackson:
    serialization:
      fail-on-empty-beans: false

#  datasource:
#    url: jdbc:mysql://localhost/kotlinBidFlow?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: pk2258
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      auto-commit: false

  datasource:
    url: jdbc:h2:mem:testdb # 인메모리 DB 사용. 파일 기반으로 변경하려면 jdbc:h2:file:/경로/파일명
    driver-class-name: org.h2.Driver
    username: sa           # 기본 사용자 이름
    password:              # 기본 비밀번호 (빈 값)
    h2:
      console:
        enabled: true        # H2 웹 콘솔 활성화
        path: /h2-console    # H2 콘솔 접속 경로 (예: http://localhost:8080/h2-console)
    jpa:
      hibernate:
        ddl-auto: update   # 테이블 자동 생성/업데이트 (create, update, create-drop, validate 중 선택)
      show-sql: true       # SQL 쿼리 로그 출력
      properties:
        hibernate:
          format_sql: true # SQL 포맷팅해서 출력

  mail:
    host: smtp.gmail.com # Gmail SMTP 서버 호스트
    port: 465 # Gmail SMTP 포트 (SSL을 사용할 경우 465)
    username: bid.system.info@gmail.com # 이메일 발송에 사용할 Gmail 주소
    password: tskqfpdczojlwfbh # 구글 앱 비밀번호 (2단계 인증 시 필요)
    protocol: smtps # 이메일 전송에 사용할 프로토콜 (smtps는 SSL 보안 사용)

    properties:
      mail:
        smtp:
          auth: true # SMTP 서버 인증 사용 여부 (true로 설정)
          timeout: 20000 # SMTP 서버와의 통신 시 대기 시간 (20초, 밀리초 단위)
          connectiontimeout: 20000 # SMTP 서버와의 연결 시도 시간 (20초, 밀리초 단위)
          writetimeout: 20000 # SMTP 서버로 데이터 전송 시 대기 시간 (20초, 밀리초 단위)
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
  slack:
    webhook-uri: https://hooks.slack.com/services/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
  config: classpath:logback-spring.xml

springdoc:
  default-produces-media-type: application/json;charset=UTF-8